"""
Data model for Chat Response entity
"""
from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime


class SourceReference(BaseModel):
    """
    Represents a reference to the book content that supports the response
    """
    module: str
    chapter: str
    section: str
    content: str
    similarity_score: float  # how relevant this content is to the query (0-1)

    class Config:
        # Validation: Similarity score must be between 0 and 1
        @classmethod
        def validate_similarity_score(cls, v):
            if not 0 <= v <= 1:
                raise ValueError('Similarity score must be between 0 and 1')
            return v


class ChatResponse(BaseModel):
    """
    Represents the answer generated by the system
    """
    response_text: str  # the AI-generated answer
    sources: List[SourceReference]  # where the information came from
    session_id: str  # identifier for the conversation session
    timestamp: Optional[datetime] = None  # when the response was generated

    class Config:
        # Validation: Response text must not be empty
        @classmethod
        def validate_response_text(cls, v):
            if not v or not v.strip():
                raise ValueError('Response text must not be empty')
            return v